version: '3'

services:
  qscweb-next-2021:
    build: qscweb-next-2021
    networks:
    - traefik_net
    - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
      - "traefik.tags=http"
      - "traefik.port=5000"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_net"
      - "traefik.backend=qscweb-next-2021"
      - "traefik.frontend.rule=Host:webnext2021.zjuqsc.com"
networks:
  traefik_net:
    external: true
